name: myfhb
description: An AI powered digital locker to store family's health records.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+10

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  gmiwidgetspackage:
    path: ../../qurhealth/fhbCommon

  # The following adds the Cupertino Icons font to your application.
  firebase_core: ^2.5.0
  rxdart: ^0.27.1
  shimmer: ^2.0.0
  cached_network_image: ^3.0.0
  camera: ^0.9.1+3
  path_provider: ^2.0.15
  path: ^1.6.4
  flutter_svg: ^2.0.9
  curved_navigation_bar: ^1.0.1
  shared_preferences: ^2.2.2
  avatar_glow: ^2.0.1
  google_maps_flutter: ^2.0.6
  auto_size_text: ^3.0.0
  dio: ^4.0.0
  flutter_sound: ^8.3.9
  flutter_geocoder: ^0.2.2-nullsafety
  geolocator: ^7.2.0+1
  uuid: ^3.0.4
  dotted_border: ^2.0.0
  webview_flutter: ^2.0.9
  video_player: ^2.1.6
  image_picker: ^0.8.1+2
  carousel_slider: ^4.0.0
  flutter_absolute_path:
    path: ./flutter_absolute_path
  provider: ^6.0.0
    #audio_waveforms package was added locally because of Compatibility  issue.
  audio_waveforms:
    path: ./audio_waveforms
  get: ^4.1.4
  sqflite: ^2.0.0+3
  devicelocale: ^0.4.1
  flutter_local_notifications: ^15.1.1
  image_gallery_saver: ^1.5.0
  permission_handler: ^9.0.2
  connectivity: ^3.0.6
  launch_review: ^3.0.1
  photo_view: ^0.14.0
  file_picker: ^3.0.3
  showcaseview: ^1.1.0
  expandable: ^5.0.1
  progress_dialog_null_safe: ^1.0.7
  google_sign_in: ^5.0.4
  quiver: ^3.0.1
  agora_rtc_engine: ^5.0.0
  firebase_messaging: ^14.2.2
  flutter_switch: ^0.3.2
  firebase_auth: ^4.2.8
  cloud_firestore: ^4.4.2
  firebase_storage: ^11.0.13
  gallery_saver: ^2.0.1
  flutter_typeahead: ^3.1.3
  money_formatter: ^0.0.3
  url_launcher: ^6.1.14
  grouped_list: ^4.0.0
  youtube_player_flutter: ^8.0.0
  scrollable_positioned_list: ^0.2.2
  package_info: ^2.0.2
  firebase_remote_config: ^3.0.12
  firebase_analytics: ^10.1.3
  flutter_html: ^3.0.0-beta.1
  scroll_to_index: ^2.0.0
  flutter_inappwebview: ^5.3.2
  flutter_downloader: ^1.5.2
#  contacts_service: ^0.6.1
  group_list_view: ^1.0.5
  advance_pdf_viewer2: ^2.0.5
  open_filex: ^4.0.0
  local_auth:
    path: ./local_auth
  firebase_dynamic_links: ^5.0.14
  lottie: ^1.1.0
  sms_autofill: ^2.0.1
  syncfusion_flutter_datepicker: ^19.3.53
  infinite_scroll_pagination: ^3.1.0
  flutter_localizations:
    sdk: flutter
  socket_io_client: ^2.0.0
  # facebook_app_events: ^0.16.0
  html_unescape: ^2.0.0
  #This Package used to navigate to device settings
  app_settings: ^4.1.6


  audioplayers: 0.20.1
  mime_type: ^1.0.0
  pin_input_text_field: 4.1.1
  table_calendar: 3.0.9
  flutter_spinkit: ^5.1.0
  badges: ^2.0.3
  flutter_timezone: ^1.0.8

dev_dependencies:
  flutter_launcher_icons: ^0.9.0
  flutter_test:
    sdk: flutter

flutter_icons:
  image_path: "assets/launcher/myfhb.png"
  android: true
  ios: true

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/user/gold-member.png
    - assets/icons/
    - assets/Qurhome/Qurhome.png
    - assets/Qurhome/
    - assets/navicons/
    - assets/voice_clone/
    - assets/maya/
    - assets/settings/
    - assets/devices/
    - assets/providers/
    - assets/help_docs/
    - assets/
    - assets/IntroScreensImages/
    - assets/devices/
    - secrets.json
    - assets/payment/failure.png
    - assets/payment/success_tick.png
    - assets/launcher/myfhb.png
    - assets/dashboard/
    - assets/loading_wave.json
    - assets/languages/
    - assets/raw/dailer_tone.mp3
    - assets/raw/ns_final.mp3


  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Light.ttf
          weight: 300
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
