name: myfhb
description: An AI powered digital locker to store family's health records.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+10

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  
  gmiwidgetspackage:
    path: C:\Users\ParvathiM\commonWidget\myfhb-flutter-common

  # The following adds the Cupertino Icons font to your application.
  firebase_core: ^1.3.0
  flutter_launcher_icons: ^0.9.0
  flutter_country_picker: ^0.1.6
  font_awesome_flutter: ^9.1.0
  rxdart: ^0.27.1
  http: ^0.13.3
  intl: ^0.17.0
  shimmer: ^2.0.0
  cached_network_image: ^3.0.0
  camera: ^0.8.1+3
  path_provider: ^2.0.2
  path: ^1.6.4
  gradient_bottom_navigation_bar: ^1.0.0+4
  flutter_svg: ^0.22.0
  flutter_arc_speed_dial: ^2.0.0
  curved_navigation_bar: ^1.0.1
  shared_preferences: ^2.0.6
  avatar_glow: ^2.0.1
  google_maps_flutter: ^2.0.6
  auto_size_text: ^2.1.0
  dio: ^4.0.0
  flutter_sound: ^8.1.4
#  flutter_google_places: ^0.3.0
  geocoder: ^0.2.1
  geolocator: ^7.2.0+1
  uuid: ^3.0.4
  dotted_border: ^2.0.0
  webview_flutter: ^2.0.9
  video_player: ^2.1.6
  image_picker: ^0.8.1+2
  carousel_slider: ^4.0.0
  multi_image_picker: ^4.7.10
  flutter_absolute_path: ^1.0.6
  provider: ^5.0.0
  get: ^4.1.4
  tflite: ^1.1.2
  sqflite: ^2.0.0+3
  devicelocale: ^0.4.1
  flutter_local_notifications: ^6.0.0
  random_color: ^1.0.5
  image_gallery_saver: ^1.5.0
  permission_handler: ^8.1.2
  connectivity: ^3.0.6
  launch_review: ^3.0.1
  intro_slider: ^3.0.2
  photo_view: ^0.11.1
  file_picker: ^3.0.3
  showcaseview: ^1.1.0
  #flashlight: ^0.1.1
  image_cropper: ^1.2.1
  loading: ^1.0.2
  expandable: ^5.0.1
  fluttertoast: ^7.0.1
  progress_dialog: ^1.2.4
  google_sign_in: ^5.0.4
  health: ^3.0.0
  quiver: ^3.0.1
  agora_rtc_engine: ^4.0.6
  firebase_messaging: ^10.0.2
  flutter_switch: ^0.3.2
  audioplayer: ^0.8.1
  firebase_auth: ^1.4.1
  cloud_firestore: ^2.2.2
  firebase_storage: ^8.1.3
  device_id: ^0.2.0
  gallery_saver: ^2.0.1
  image_downloader: ^0.30.0
  flutter_typeahead: ^3.1.3
  screen: ^0.0.5
  money_formatter: ^0.0.3
  url_launcher: ^6.0.7
  grouped_list: ^4.0.0
  country_pickers: ^2.0.0
  youtube_player_flutter: ^8.0.0
  scrollable_positioned_list: ^0.1.8
  appsflyer_sdk: ^6.2.0+1
  package_info: ^2.0.2
  firebase_remote_config: ^0.10.0+2
  firebase_analytics: ^8.1.2
  flutter_html: ^2.1.0
  scroll_to_index: ^2.0.0
  flutter_inappwebview: ^5.3.2
  flutter_downloader: ^1.5.2
  contacts_service: ^0.6.1
  group_list_view: ^1.0.5
  advance_pdf_viewer: ^2.0.0
  open_file: ^3.2.1
  firebase_dynamic_links: ^2.0.7
  lottie: ^1.1.0
  flutter_logs: ^2.1.4
  sms_autofill: ^2.0.1
  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter_icons:
  image_path: "assets/launcher/myfhb.png"
  android: true
  ios: true

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/user/avatar.png
    - assets/user/profile_pic_ph.png
    - assets/user/gold-member.png
    - assets/icons/
    - assets/launcher/myfhb.png
    - assets/navicons/
    - assets/norecordfound.png
    - assets/bg/family_bg.png
    - assets/login_icon.png
    - assets/maya/
    - assets/settings/
    - assets/devices/
    - assets/providers/
    - assets/help_docs/
    - assets/video/
    - assets/slide_icons/
    - assets/
    - assets/launcher/qurplan.png
    - assets/IntroScreensImages/
    - assets/devices/
    - secrets.json
    - assets/payment/failure.png
    - assets/payment/success_tick.png
    - assets/launcher/myfhb.png
    - assets/launcher/myfhb1.png
    - assets/dashboard/
    - assets/loading_wave.json
    - assets/languages/

  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Light.ttf
          weight: 300
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
