name: myfhb
description: An AI powered digital locker to store family's health records.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+10

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  
  gmiwidgetspackage:
    path: C:\source.code\flutter\fhb_common\myfhb-flutter-common\

  # The following adds the Cupertino Icons font to your application.
  flutter_launcher_icons: ^0.7.0
  flutter_country_picker: ^0.1.6
  font_awesome_flutter: ^8.5.0
  rxdart: ^0.22.0
  http: ^0.12.0+3
  intl: ^0.16.1
  shimmer: ^1.0.1
  cached_network_image: ^2.0.0
  camera: ^0.5.8+5
  path_provider: ^1.6.0
  path: ^1.6.4
  gradient_bottom_navigation_bar: ^1.0.0+4
  flutter_svg: ^0.18.0
  flutter_arc_speed_dial: ^1.0.2
  curved_navigation_bar: ^0.3.1
  shared_preferences: ^0.5.6
  avatar_glow: ^1.1.0
  google_maps_flutter: ^0.5.22
  auto_size_text: ^2.1.0
  dio: ^3.0.10
  flutter_sound: ^2.0.4
  flutter_google_places: ^0.2.3
  geocoder: ^0.2.1
  geolocator: ^5.2.1
  uuid: ^2.0.4
  dotted_border: ^1.0.4
  webview_flutter: ^0.3.22+1
  video_player: ^0.10.7
  image_picker: ^0.6.7+4
  carousel_slider: ^1.4.1
  multi_image_picker: ^4.7.10
  flutter_absolute_path: ^1.0.6
  provider: ^4.3.2
  get: ^2.14.1
  tflite: ^1.0.5
  sqflite: ^1.2.0
  devicelocale: ^0.2.2 
  flutter_local_notifications:
  random_color: ^1.0.5
  image_gallery_saver: ^1.5.0
  permission_handler: ^5.0.1+1
  connectivity: ^0.4.8+2
  launch_review: ^2.0.0
  intro_slider: ^2.2.9
  photo_view: ^0.9.2
  file_picker: ^1.8.0+2
  showcaseview: ^0.1.5
  flashlight: ^0.1.1
  image_cropper: ^1.2.1
  #android_intent: ^0.3.7+1
  pdf_render: ^0.57.2
  loading: ^1.0.2
  expandable: ^4.1.4
  fluttertoast: ^7.0.1
  progress_dialog: ^1.2.4
  google_sign_in: ^4.5.1
  health: ^1.1.5
  quiver: ^2.1.3
  agora_rtc_engine: 1.0.5
  firebase_messaging: ^6.0.15
  flutter_switch: ^0.1.1
  audioplayer: ^0.8.1
  flutter_timer: ^0.0.6
  firebase_auth: ^0.14.0+5
  cloud_firestore: ^0.12.9+5
  firebase_storage: ^3.0.6
  device_id: ^0.2.0
  gallery_saver: ^2.0.1
  image_downloader: ^0.20.0
  simple_pdf_viewer: ^0.2.2
  flutter_typeahead: ^1.8.8
  open_file: ^3.0.1
  flutter_money_formatter:
    git:
      url: git://github.com/anisalibegic/flutter_money_formatter.git
  screen: ^0.0.5



dev_dependencies:
  flutter_test:
    sdk: flutter

flutter_icons:
  image_path: "assets/launcher/myfhb.png"
  android: true
  ios: true

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/user/avatar.png
    - assets/icons/
    - assets/launcher/myfhb.png
    - assets/navicons/
    - assets/norecordfound.png
    - assets/bg/family_bg.png
    - assets/login_icon.png
    - assets/maya/
    - assets/settings/
    - assets/devices/
    - assets/providers/
    - assets/help_docs/
    - assets/video/
    - assets/slide_icons/
    - assets/
    - assets/devices/
    - secrets.json
    - assets/payment/failure.png
    - assets/payment/success_tick.png


  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Light.ttf
          weight: 300          
        - asset: assets/fonts/Poppins-Regular.ttf          
          weight: 400
        - asset: assets/fonts/Poppins-Medium.ttf          
          weight: 500
        - asset: assets/fonts/Poppins-SemiBold.ttf          
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
