const message = 'message';
const unreadNotification = 'unreadNotification';
const getChatsList = 'getChatList';
const notifyChatList = 'notifyChatList';
const notifyQurhomeUser = 'notifyQurhomeUser';
const upload_failed = 'Upload failed, Try again later';
const String isDoctor = '&isDoctor=false';
const String careCoordiantorId = '&careCoordinatorId=';
const String isNormalChatList = '&isChatList=';
const String getChatTotalCountEmit = 'getUnreadMessageCount';
const String getChatTotalCountOn = 'setUnreadMessageCount';
