package com.ventechsolutions.myFHB.constants

object Constants {
    val FUN_APP_VERSION = "getAppVersion"
    val FUN_LISTEN_SMS = "listenForSMS"
    val FUN_KEY_GAURD = "secureMe"
    val FUN_VOICE_ASST = "speakWithVoiceAssistant"
    val VOICE_ASST_PROMPT = "Need to speak"
    val FUN_TEXT2SPEECH = "textToSpeech"
    val KEY_GAURD_TITLE = "myFHB"
    val KEY_GAURD_TITLE_DESC = "Please Authorize to use the Application"
    val KEY_GAURD_AUTH_SUCC = 1002
    val KEY_GAURD_AUTH_FAIL = 1002
    val TXT_PLAIN = "text/plain"
    val TICKER = "Ticker values"
    val CN_VC = "flutter.native/versioncode"
    val CN_LISTEN4SMS = "flutter.native/listen4sms"
    val CN_VOICE_INTENT = "flutter.native/voiceIntent"
    val CN_TTS = "flutter.native/textToSpeech"
    val CN_SECURE = "flutter.native/security"
    val CN_ROUTE = "navigation.channel"
    val CN_ONG_NS = "ongoing_ns.channel"
    val CN_EVE_STREAM = "com.example.agoraflutterquickstart/stream"
    val FROM_LANG = "com.example.agoraflutterquickstart/stream"
    val TO_LANG = "com.example.agoraflutterquickstart/stream"
    val EN_US = "en_US"
    val FUN_GET_MY_ROUTE = "getMyRoute"
    val FUN_ONG_NS = "startOnGoingNS"
    val PROP_MODE = "mode"
    val PROP_MSG = "message"
    val PROP_IS_CLOSE = "isClose"
    val PROP_START = "start"
    val PROP_STOP = "stop"
    val PROP_NAME = "name"
    val PROP_CALL = "call"
    val PROP_ACK = "ack"
}
