// // return RegimentResponseModel.fromJson([
// //   {
// //     "eid": "1473",
// //     "providerid": "1",
// //     "uid": "29",
// //     "title": " Pre Breakfast , 10 Mins After Wakeup",
// //     "description": "Pre Breakfast",
// //     "tplanid": "11",
// //     "teid_user": "16",
// //     "aid": "13",
// //     "activityname": "diet",
// //     "uformid": "0",
// //     "uformname": "",
// //     "estart": "2021-04-14 06:10:00",
// //     "eend": "2021-04-14 06:15:00",
// //     "html": null,
// //     "otherinfo": {
// //       "NeedPhoto": 0,
// //       "NeedAudio": 0,
// //       "NeedVideo": 0,
// //       "NeedFile": 0
// //     },
// //     "remindin": "0",
// //     "remindin_type": "0",
// //     "ack": null,
// //     "alarm": "0",
// //     "uformdata": null,
// //     "ts": "2021-04-14 09:03:15",
// //     "deleted": "0",
// //     "hashtml": 0,
// //     "hascustform": 1,
// //     "hasform": 1,
// //     "saytext": "Eat Pre Breakfast , 10 Mins After Wakeup at 06:10 AM"
// //   },
// //   {
// //     "eid": "943",
// //     "providerid": "1",
// //     "uid": "29",
// //     "title": " BloodPressure , 20 Mins Before and After Meal",
// //     "description": "",
// //     "tplanid": "10",
// //     "teid_user": "2",
// //     "aid": "2",
// //     "activityname": "vitals",
// //     "uformid": "1",
// //     "uformname": "bloodpressure",
// //     "estart": "2021-04-14 08:40:00",
// //     "eend": "2021-04-14 08:45:00",
// //     "html": null,
// //     "otherinfo": {
// //       "NeedPhoto": 0,
// //       "NeedAudio": 0,
// //       "NeedVideo": 0,
// //       "NeedFile": 0
// //     },
// //     "remindin": "0",
// //     "remindin_type": "0",
// //     "ack": "2021-04-14 14:33:26",
// //     "alarm": "1",
// //     "uformdata":
// //         "{\"Systolic\":{\"value\":\"111\",\"type\":\"number\",\"display\":\"111\",\"alarm\":0,\"amin\":\"40\",\"amax\":\"140\"},\"Diastolic\":{\"value\":\"222\",\"type\":\"number\",\"display\":\"222\",\"alarm\":1,\"amin\":\"35\",\"amax\":\"90\"},\"Pulse\":{\"value\":\"333\",\"type\":\"number\",\"display\":\"333\",\"alarm\":1,\"amin\":\"30\",\"amax\":\"130\"}}",
// //     "ts": "2021-04-14 09:03:26",
// //     "deleted": "0",
// //     "hashtml": 0,
// //     "hascustform": 0,
// //     "hasform": 1,
// //     "saytext":
// //         "Check Vital BloodPressure , 20 Mins Before and After Meal at 08:40 AM"
// //   },
// //   {
// //     "eid": "1203",
// //     "providerid": "1",
// //     "uid": "29",
// //     "title": " Glucose Fasting BloodSugar , 10 Mins Before Meal",
// //     "description": "Glucose Fasting",
// //     "tplanid": "10",
// //     "teid_user": "4",
// //     "aid": "2",
// //     "activityname": "vitals",
// //     "uformid": "5",
// //     "uformname": "bloodsugar",
// //     "estart": "2021-04-14 08:50:00",
// //     "eend": "2021-04-14 08:55:00",
// //     "html": null,
// //     "otherinfo": {
// //       "NeedPhoto": 0,
// //       "NeedAudio": 0,
// //       "NeedVideo": 0,
// //       "NeedFile": 0
// //     },
// //     "remindin": "0",
// //     "remindin_type": "0",
// //     "ack": "2021-04-14 14:33:30",
// //     "alarm": "0",
// //     "uformdata":
// //         "{\"BloodSugar\":{\"value\":\"123\",\"type\":\"number\",\"display\":\"123\",\"alarm\":0,\"amin\":\"\",\"amax\":\"\"}}",
// //     "ts": "2021-04-14 09:03:30",
// //     "deleted": "0",
// //     "hashtml": 0,
// //     "hascustform": 0,
// //     "hasform": 1,
// //     "saytext":
// //         "Check Vital Glucose Fasting BloodSugar , 10 Mins Before Meal at 08:50 AM"
// //   },
// //   {
// //     "eid": "1237",
// //     "providerid": "1",
// //     "uid": "29",
// //     "title": " Glucose Preprandial BloodSugar , 10 Mins Before Meal",
// //     "description": "Glucose Preprandial",
// //     "tplanid": "10",
// //     "teid_user": "5",
// //     "aid": "2",
// //     "activityname": "vitals",
// //     "uformid": "5",
// //     "uformname": "bloodsugar",
// //     "estart": "2021-04-14 08:50:00",
// //     "eend": "2021-04-14 08:55:00",
// //     "html": null,
// //     "otherinfo": {
// //       "NeedPhoto": 0,
// //       "NeedAudio": 0,
// //       "NeedVideo": 0,
// //       "NeedFile": 0
// //     },
// //     "remindin": "0",
// //     "remindin_type": "0",
// //     "ack": null,
// //     "alarm": "0",
// //     "uformdata": null,
// //     "ts": "2021-04-14 09:03:15",
// //     "deleted": "0",
// //     "hashtml": 0,
// //     "hascustform": 0,
// //     "hasform": 1,
// //     "saytext":
// //         "Check Vital Glucose Preprandial BloodSugar , 10 Mins Before Meal at 08:50 AM"
// //   },
// //   {
// //     "eid": "1503",
// //     "providerid": "1",
// //     "uid": "29",
// //     "title": " Breakfast",
// //     "description": "Breakfast",
// //     "tplanid": "11",
// //     "teid_user": "17",
// //     "aid": "13",
// //     "activityname": "diet",
// //     "uformid": "0",
// //     "uformname": "",
// //     "estart": "2021-04-14 09:00:00",
// //     "eend": "2021-04-14 09:05:00",
// //     "html": null,
// //     "otherinfo": {
// //       "NeedPhoto": "1",
// //       "NeedAudio": 0,
// //       "NeedVideo": 0,
// //       "NeedFile": 0
// //     },
// //     "remindin": "0",
// //     "remindin_type": "0",
// //     "ack": null,
// //     "alarm": "0",
// //     "uformdata": null,
// //     "ts": "2021-04-14 09:03:15",
// //     "deleted": "0",
// //     "hashtml": 0,
// //     "hascustform": 1,
// //     "hasform": 1,
// //     "saytext": "Eat Breakfast at 09:00 AM"
// //   },
// //   {
// //     "eid": "847",
// //     "providerid": "1",
// //     "uid": "29",
// //     "title": " Metformin 500 , 10 Mins After Meal",
// //     "description": "",
// //     "tplanid": "10",
// //     "teid_user": "1",
// //     "aid": "1",
// //     "activityname": "medication",
// //     "uformid": "0",
// //     "uformname": "",
// //     "estart": "2021-04-14 09:10:00",
// //     "eend": "2021-04-14 09:15:00",
// //     "html": null,
// //     "otherinfo": {
// //       "NeedPhoto": 0,
// //       "NeedAudio": 0,
// //       "NeedVideo": 0,
// //       "NeedFile": 0
// //     },
// //     "remindin": "0",
// //     "remindin_type": "0",
// //     "ack": null,
// //     "alarm": "0",
// //     "uformdata": null,
// //     "ts": "2021-04-14 09:03:14",
// //     "deleted": "0",
// //     "hashtml": 1,
// //     "hascustform": 0,
// //     "hasform": 0,
// //     "saytext": "Take Metformin 500 , 10 Mins After Meal at 09:10 AM"
// //   },
// //   {
// //     "eid": "944",
// //     "providerid": "1",
// //     "uid": "29",
// //     "title": " BloodPressure , 20 Mins Before and After Meal",
// //     "description": "",
// //     "tplanid": "10",
// //     "teid_user": "2",
// //     "aid": "2",
// //     "activityname": "vitals",
// //     "uformid": "1",
// //     "uformname": "bloodpressure",
// //     "estart": "2021-04-14 09:20:00",
// //     "eend": "2021-04-14 09:25:00",
// //     "html": null,
// //     "otherinfo": {
// //       "NeedPhoto": 0,
// //       "NeedAudio": 0,
// //       "NeedVideo": 0,
// //       "NeedFile": 0
// //     },
// //     "remindin": "0",
// //     "remindin_type": "0",
// //     "ack": "2021-04-14 14:33:38",
// //     "alarm": "1",
// //     "uformdata":
// //         "{\"Systolic\":{\"value\":\"333\",\"type\":\"number\",\"display\":\"333\",\"alarm\":1,\"amin\":\"40\",\"amax\":\"140\"},\"Diastolic\":{\"value\":\"222\",\"type\":\"number\",\"display\":\"222\",\"alarm\":1,\"amin\":\"35\",\"amax\":\"90\"},\"Pulse\":{\"value\":\"111\",\"type\":\"number\",\"display\":\"111\",\"alarm\":0,\"amin\":\"30\",\"amax\":\"130\"}}",
// //     "ts": "2021-04-14 09:03:38",
// //     "deleted": "0",
// //     "hashtml": 0,
// //     "hascustform": 0,
// //     "hasform": 1,
// //     "saytext":
// //         "Check Vital BloodPressure , 20 Mins Before and After Meal at 09:20 AM"
// //   },
// //   {
// //     "eid": "1117",
// //     "providerid": "1",
// //     "uid": "29",
// //     "title": " BloodSugar , 10 Mins Before Meal",
// //     "description": "",
// //     "tplanid": "10",
// //     "teid_user": "3",
// //     "aid": "2",
// //     "activityname": "vitals",
// //     "uformid": "5",
// //     "uformname": "bloodsugar",
// //     "estart": "2021-04-14 10:00:00",
// //     "eend": "2021-04-14 10:05:00",
// //     "html": null,
// //     "otherinfo": {
// //       "NeedPhoto": 0,
// //       "NeedAudio": 0,
// //       "NeedVideo": 0,
// //       "NeedFile": 0
// //     },
// //     "remindin": "0",
// //     "remindin_type": "0",
// //     "ack": null,
// //     "alarm": "0",
// //     "uformdata": null,
// //     "ts": "2021-04-14 09:03:15",
// //     "deleted": "0",
// //     "hashtml": 0,
// //     "hascustform": 0,
// //     "hasform": 1,
// //     "saytext":
// //         "Check Vital BloodSugar , 10 Mins Before Meal at 10:00 AM"
// //   },
// //   {
// //     "eid": "1327",
// //     "providerid": "1",
// //     "uid": "29",
// //     "title": " Glucose Postprandial BloodSugar , 120 Mins After Meal",
// //     "description": "Glucose Postprandial",
// //     "tplanid": "10",
// //     "teid_user": "6",
// //     "aid": "2",
// //     "activityname": "vitals",
// //     "uformid": "5",
// //     "uformname": "bloodsugar",
// //     "estart": "2021-04-14 11:00:00",
// //     "eend": "2021-04-14 11:05:00",
// //     "html": null,
// //     "otherinfo": {
// //       "NeedPhoto": 0,
// //       "NeedAudio": 0,
// //       "NeedVideo": 0,
// //       "NeedFile": 0
// //     },
// //     "remindin": "0",
// //     "remindin_type": "0",
// //     "ack": null,
// //     "alarm": "0",
// //     "uformdata": null,
// //     "ts": "2021-04-14 09:03:15",
// //     "deleted": "0",
// //     "hashtml": 0,
// //     "hascustform": 0,
// //     "hasform": 1,
// //     "saytext":
// //         "Check Vital Glucose Postprandial BloodSugar , 120 Mins After Meal at 11:00 AM"
// //   },
// //   {
// //     "eid": "1533",
// //     "providerid": "1",
// //     "uid": "29",
// //     "title": " Mid Morning , 10 Mins Before Meal",
// //     "description": "Mid Morning",
// //     "tplanid": "11",
// //     "teid_user": "18",
// //     "aid": "13",
// //     "activityname": "diet",
// //     "uformid": "0",
// //     "uformname": "",
// //     "estart": "2021-04-14 11:00:00",
// //     "eend": "2021-04-14 11:05:00",
// //     "html": null,
// //     "otherinfo": {
// //       "NeedPhoto": "1",
// //       "NeedAudio": 0,
// //       "NeedVideo": 0,
// //       "NeedFile": 0
// //     },
// //     "remindin": "0",
// //     "remindin_type": "0",
// //     "ack": null,
// //     "alarm": "0",
// //     "uformdata": null,
// //     "ts": "2021-04-14 09:03:15",
// //     "deleted": "0",
// //     "hashtml": 0,
// //     "hascustform": 1,
// //     "hasform": 1,
// //     "saytext": "Eat Mid Morning , 10 Mins Before Meal at 11:00 AM"
// //   },
// //   {
// //     "eid": "945",
// //     "providerid": "1",
// //     "uid": "29",
// //     "title": " BloodPressure , 20 Mins Before and After Meal",
// //     "description": "",
// //     "tplanid": "10",
// //     "teid_user": "2",
// //     "aid": "2",
// //     "activityname": "vitals",
// //     "uformid": "1",
// //     "uformname": "bloodpressure",
// //     "estart": "2021-04-14 12:40:00",
// //     "eend": "2021-04-14 12:45:00",
// //     "html": null,
// //     "otherinfo": {
// //       "NeedPhoto": 0,
// //       "NeedAudio": 0,
// //       "NeedVideo": 0,
// //       "NeedFile": 0
// //     },
// //     "remindin": "0",
// //     "remindin_type": "0",
// //     "ack": null,
// //     "alarm": "0",
// //     "uformdata": null,
// //     "ts": "2021-04-14 09:03:14",
// //     "deleted": "0",
// //     "hashtml": 0,
// //     "hascustform": 0,
// //     "hasform": 1,
// //     "saytext":
// //         "Check Vital BloodPressure , 20 Mins Before and After Meal at 12:40 PM"
// //   },
// //   {
// //     "eid": "1563",
// //     "providerid": "1",
// //     "uid": "29",
// //     "title": " lunch , 10 Mins Before Meal",
// //     "description": "lunch",
// //     "tplanid": "11",
// //     "teid_user": "19",
// //     "aid": "13",
// //     "activityname": "diet",
// //     "uformid": "0",
// //     "uformname": "",
// //     "estart": "2021-04-14 12:50:00",
// //     "eend": "2021-04-14 12:55:00",
// //     "html": null,
// //     "otherinfo": {
// //       "NeedPhoto": "1",
// //       "NeedAudio": 0,
// //       "NeedVideo": 0,
// //       "NeedFile": 0
// //     },
// //     "remindin": "0",
// //     "remindin_type": "0",
// //     "ack": null,
// //     "alarm": "0",
// //     "uformdata": null,
// //     "ts": "2021-04-14 09:03:15",
// //     "deleted": "0",
// //     "hashtml": 0,
// //     "hascustform": 1,
// //     "hasform": 1,
// //     "saytext": "Eat lunch , 10 Mins Before Meal at 12:50 PM"
// //   },
// //   {
// //     "eid": "1238",
// //     "providerid": "1",
// //     "uid": "29",
// //     "title": " Glucose Preprandial BloodSugar , 10 Mins Before Meal",
// //     "description": "Glucose Preprandial",
// //     "tplanid": "10",
// //     "teid_user": "5",
// //     "aid": "2",
// //     "activityname": "vitals",
// //     "uformid": "5",
// //     "uformname": "bloodsugar",
// //     "estart": "2021-04-14 12:50:00",
// //     "eend": "2021-04-14 12:55:00",
// //     "html": null,
// //     "otherinfo": {
// //       "NeedPhoto": 0,
// //       "NeedAudio": 0,
// //       "NeedVideo": 0,
// //       "NeedFile": 0
// //     },
// //     "remindin": "0",
// //     "remindin_type": "0",
// //     "ack": null,
// //     "alarm": "0",
// //     "uformdata": null,
// //     "ts": "2021-04-14 09:03:15",
// //     "deleted": "0",
// //     "hashtml": 0,
// //     "hascustform": 0,
// //     "hasform": 1,
// //     "saytext":
// //         "Check Vital Glucose Preprandial BloodSugar , 10 Mins Before Meal at 12:50 PM"
// //   },
// //   {
// //     "eid": "1118",
// //     "providerid": "1",
// //     "uid": "29",
// //     "title": " BloodSugar , 10 Mins Before Meal",
// //     "description": "",
// //     "tplanid": "10",
// //     "teid_user": "3",
// //     "aid": "2",
// //     "activityname": "vitals",
// //     "uformid": "5",
// //     "uformname": "bloodsugar",
// //     "estart": "2021-04-14 13:00:00",
// //     "eend": "2021-04-14 13:05:00",
// //     "html": null,
// //     "otherinfo": {
// //       "NeedPhoto": 0,
// //       "NeedAudio": 0,
// //       "NeedVideo": 0,
// //       "NeedFile": 0
// //     },
// //     "remindin": "0",
// //     "remindin_type": "0",
// //     "ack": null,
// //     "alarm": "0",
// //     "uformdata": null,
// //     "ts": "2021-04-14 09:03:15",
// //     "deleted": "0",
// //     "hashtml": 0,
// //     "hascustform": 0,
// //     "hasform": 1,
// //     "saytext":
// //         "Check Vital BloodSugar , 10 Mins Before Meal at 01:00 PM"
// //   },
// //   {
// //     "eid": "848",
// //     "providerid": "1",
// //     "uid": "29",
// //     "title": " Metformin 500 , 10 Mins After Meal",
// //     "description": "",
// //     "tplanid": "10",
// //     "teid_user": "1",
// //     "aid": "1",
// //     "activityname": "medication",
// //     "uformid": "0",
// //     "uformname": "",
// //     "estart": "2021-04-14 13:10:00",
// //     "eend": "2021-04-14 13:15:00",
// //     "html": null,
// //     "otherinfo": {
// //       "NeedPhoto": 0,
// //       "NeedAudio": 0,
// //       "NeedVideo": 0,
// //       "NeedFile": 0
// //     },
// //     "remindin": "0",
// //     "remindin_type": "0",
// //     "ack": null,
// //     "alarm": "0",
// //     "uformdata": null,
// //     "ts": "2021-04-14 09:03:14",
// //     "deleted": "0",
// //     "hashtml": 1,
// //     "hascustform": 0,
// //     "hasform": 0,
// //     "saytext": "Take Metformin 500 , 10 Mins After Meal at 01:10 PM"
// //   },
// //   {
// //     "eid": "946",
// //     "providerid": "1",
// //     "uid": "29",
// //     "title": " BloodPressure , 20 Mins Before and After Meal",
// //     "description": "",
// //     "tplanid": "10",
// //     "teid_user": "2",
// //     "aid": "2",
// //     "activityname": "vitals",
// //     "uformid": "1",
// //     "uformname": "bloodpressure",
// //     "estart": "2021-04-14 13:20:00",
// //     "eend": "2021-04-14 13:25:00",
// //     "html": null,
// //     "otherinfo": {
// //       "NeedPhoto": 0,
// //       "NeedAudio": 0,
// //       "NeedVideo": 0,
// //       "NeedFile": 0
// //     },
// //     "remindin": "0",
// //     "remindin_type": "0",
// //     "ack": null,
// //     "alarm": "0",
// //     "uformdata": null,
// //     "ts": "2021-04-14 09:03:14",
// //     "deleted": "0",
// //     "hashtml": 0,
// //     "hascustform": 0,
// //     "hasform": 1,
// //     "saytext":
// //         "Check Vital BloodPressure , 20 Mins Before and After Meal at 01:20 PM"
// //   },
// //   {
// //     "eid": "1328",
// //     "providerid": "1",
// //     "uid": "29",
// //     "title": " Glucose Postprandial BloodSugar , 120 Mins After Meal",
// //     "description": "Glucose Postprandial",
// //     "tplanid": "10",
// //     "teid_user": "6",
// //     "aid": "2",
// //     "activityname": "vitals",
// //     "uformid": "5",
// //     "uformname": "bloodsugar",
// //     "estart": "2021-04-14 15:00:00",
// //     "eend": "2021-04-14 15:05:00",
// //     "html": null,
// //     "otherinfo": {
// //       "NeedPhoto": 0,
// //       "NeedAudio": 0,
// //       "NeedVideo": 0,
// //       "NeedFile": 0
// //     },
// //     "remindin": "0",
// //     "remindin_type": "0",
// //     "ack": null,
// //     "alarm": "0",
// //     "uformdata": null,
// //     "ts": "2021-04-14 09:03:15",
// //     "deleted": "0",
// //     "hashtml": 0,
// //     "hascustform": 0,
// //     "hasform": 1,
// //     "saytext":
// //         "Check Vital Glucose Postprandial BloodSugar , 120 Mins After Meal at 03:00 PM"
// //   },
// //   {
// //     "eid": "1593",
// //     "providerid": "1",
// //     "uid": "29",
// //     "title": " Evening , 10 Mins Before Meal",
// //     "description": "Evening",
// //     "tplanid": "11",
// //     "teid_user": "20",
// //     "aid": "13",
// //     "activityname": "diet",
// //     "uformid": "0",
// //     "uformname": "",
// //     "estart": "2021-04-14 16:50:00",
// //     "eend": "2021-04-14 16:55:00",
// //     "html": null,
// //     "otherinfo": {
// //       "NeedPhoto": "1",
// //       "NeedAudio": 0,
// //       "NeedVideo": 0,
// //       "NeedFile": 0
// //     },
// //     "remindin": "0",
// //     "remindin_type": "0",
// //     "ack": null,
// //     "alarm": "0",
// //     "uformdata": null,
// //     "ts": "2021-04-14 09:03:15",
// //     "deleted": "0",
// //     "hashtml": 0,
// //     "hascustform": 1,
// //     "hasform": 1,
// //     "saytext": "Eat Evening , 10 Mins Before Meal at 04:50 PM"
// //   },
// //   {
// //     "eid": "1119",
// //     "providerid": "1",
// //     "uid": "29",
// //     "title": " BloodSugar , 10 Mins Before Meal",
// //     "description": "",
// //     "tplanid": "10",
// //     "teid_user": "3",
// //     "aid": "2",
// //     "activityname": "vitals",
// //     "uformid": "5",
// //     "uformname": "bloodsugar",
// //     "estart": "2021-04-14 17:00:00",
// //     "eend": "2021-04-14 17:05:00",
// //     "html": null,
// //     "otherinfo": {
// //       "NeedPhoto": 0,
// //       "NeedAudio": 0,
// //       "NeedVideo": 0,
// //       "NeedFile": 0
// //     },
// //     "remindin": "0",
// //     "remindin_type": "0",
// //     "ack": null,
// //     "alarm": "0",
// //     "uformdata": null,
// //     "ts": "2021-04-14 09:03:15",
// //     "deleted": "0",
// //     "hashtml": 0,
// //     "hascustform": 0,
// //     "hasform": 1,
// //     "saytext":
// //         "Check Vital BloodSugar , 10 Mins Before Meal at 05:00 PM"
// //   },
// //   {
// //     "eid": "947",
// //     "providerid": "1",
// //     "uid": "29",
// //     "title": " BloodPressure , 20 Mins Before and After Meal",
// //     "description": "",
// //     "tplanid": "10",
// //     "teid_user": "2",
// //     "aid": "2",
// //     "activityname": "vitals",
// //     "uformid": "1",
// //     "uformname": "bloodpressure",
// //     "estart": "2021-04-14 19:40:00",
// //     "eend": "2021-04-14 19:45:00",
// //     "html": null,
// //     "otherinfo": {
// //       "NeedPhoto": 0,
// //       "NeedAudio": 0,
// //       "NeedVideo": 0,
// //       "NeedFile": 0
// //     },
// //     "remindin": "0",
// //     "remindin_type": "0",
// //     "ack": null,
// //     "alarm": "0",
// //     "uformdata": null,
// //     "ts": "2021-04-14 09:03:14",
// //     "deleted": "0",
// //     "hashtml": 0,
// //     "hascustform": 0,
// //     "hasform": 1,
// //     "saytext":
// //         "Check Vital BloodPressure , 20 Mins Before and After Meal at 07:40 PM"
// //   },
// //   {
// //     "eid": "1623",
// //     "providerid": "1",
// //     "uid": "29",
// //     "title": " Dinner , 10 Mins Before Meal",
// //     "description": "Dinner",
// //     "tplanid": "11",
// //     "teid_user": "21",
// //     "aid": "13",
// //     "activityname": "diet",
// //     "uformid": "0",
// //     "uformname": "",
// //     "estart": "2021-04-14 19:50:00",
// //     "eend": "2021-04-14 19:55:00",
// //     "html": null,
// //     "otherinfo": {
// //       "NeedPhoto": "1",
// //       "NeedAudio": 0,
// //       "NeedVideo": 0,
// //       "NeedFile": 0
// //     },
// //     "remindin": "0",
// //     "remindin_type": "0",
// //     "ack": null,
// //     "alarm": "0",
// //     "uformdata": null,
// //     "ts": "2021-04-14 09:03:15",
// //     "deleted": "0",
// //     "hashtml": 0,
// //     "hascustform": 1,
// //     "hasform": 1,
// //     "saytext": "Eat Dinner , 10 Mins Before Meal at 07:50 PM"
// //   },
// //   {
// //     "eid": "1239",
// //     "providerid": "1",
// //     "uid": "29",
// //     "title": " Glucose Preprandial BloodSugar , 10 Mins Before Meal",
// //     "description": "Glucose Preprandial",
// //     "tplanid": "10",
// //     "teid_user": "5",
// //     "aid": "2",
// //     "activityname": "vitals",
// //     "uformid": "5",
// //     "uformname": "bloodsugar",
// //     "estart": "2021-04-14 19:50:00",
// //     "eend": "2021-04-14 19:55:00",
// //     "html": null,
// //     "otherinfo": {
// //       "NeedPhoto": 0,
// //       "NeedAudio": 0,
// //       "NeedVideo": 0,
// //       "NeedFile": 0
// //     },
// //     "remindin": "0",
// //     "remindin_type": "0",
// //     "ack": null,
// //     "alarm": "0",
// //     "uformdata": null,
// //     "ts": "2021-04-14 09:03:15",
// //     "deleted": "0",
// //     "hashtml": 0,
// //     "hascustform": 0,
// //     "hasform": 1,
// //     "saytext":
// //         "Check Vital Glucose Preprandial BloodSugar , 10 Mins Before Meal at 07:50 PM"
// //   },
// //   {
// //     "eid": "1443",
// //     "providerid": "1",
// //     "uid": "29",
// //     "title": " Foot Examination Self , 10 Mins Before Meal",
// //     "description": "",
// //     "tplanid": "10",
// //     "teid_user": "13",
// //     "aid": "409",
// //     "activityname": "screening",
// //     "uformid": "0",
// //     "uformname": "",
// //     "estart": "2021-04-14 20:00:00",
// //     "eend": "2021-04-14 20:05:00",
// //     "html": null,
// //     "otherinfo": {
// //       "NeedPhoto": "1",
// //       "NeedAudio": "1",
// //       "NeedVideo": "1",
// //       "NeedFile": 0
// //     },
// //     "remindin": "0",
// //     "remindin_type": "0",
// //     "ack": null,
// //     "alarm": "0",
// //     "uformdata": null,
// //     "ts": "2021-04-14 09:03:15",
// //     "deleted": "0",
// //     "hashtml": 0,
// //     "hascustform": 0,
// //     "hasform": 0,
// //     "saytext":
// //         " Foot Examination Self , 10 Mins Before Meal at 08:00 PM"
// //   },
// //   {
// //     "eid": "849",
// //     "providerid": "1",
// //     "uid": "29",
// //     "title": " Metformin 500 , 10 Mins After Meal",
// //     "description": "",
// //     "tplanid": "10",
// //     "teid_user": "1",
// //     "aid": "1",
// //     "activityname": "medication",
// //     "uformid": "0",
// //     "uformname": "",
// //     "estart": "2021-04-14 20:10:00",
// //     "eend": "2021-04-14 20:15:00",
// //     "html": null,
// //     "otherinfo": {
// //       "NeedPhoto": 0,
// //       "NeedAudio": 0,
// //       "NeedVideo": 0,
// //       "NeedFile": 0
// //     },
// //     "remindin": "0",
// //     "remindin_type": "0",
// //     "ack": null,
// //     "alarm": "0",
// //     "uformdata": null,
// //     "ts": "2021-04-14 09:03:14",
// //     "deleted": "0",
// //     "hashtml": 1,
// //     "hascustform": 0,
// //     "hasform": 0,
// //     "saytext": "Take Metformin 500 , 10 Mins After Meal at 08:10 PM"
// //   },
// //   {
// //     "eid": "948",
// //     "providerid": "1",
// //     "uid": "29",
// //     "title": " BloodPressure , 20 Mins Before and After Meal",
// //     "description": "",
// //     "tplanid": "10",
// //     "teid_user": "2",
// //     "aid": "2",
// //     "activityname": "vitals",
// //     "uformid": "1",
// //     "uformname": "bloodpressure",
// //     "estart": "2021-04-14 20:20:00",
// //     "eend": "2021-04-14 20:25:00",
// //     "html": null,
// //     "otherinfo": {
// //       "NeedPhoto": 0,
// //       "NeedAudio": 0,
// //       "NeedVideo": 0,
// //       "NeedFile": 0
// //     },
// //     "remindin": "0",
// //     "remindin_type": "0",
// //     "ack": null,
// //     "alarm": "0",
// //     "uformdata": null,
// //     "ts": "2021-04-14 09:03:14",
// //     "deleted": "0",
// //     "hashtml": 0,
// //     "hascustform": 0,
// //     "hasform": 1,
// //     "saytext":
// //         "Check Vital BloodPressure , 20 Mins Before and After Meal at 08:20 PM"
// //   },
// //   {
// //     "eid": "1653",
// //     "providerid": "1",
// //     "uid": "29",
// //     "title": " Bed Time , 30 Mins Before Meal",
// //     "description": "Bed Time",
// //     "tplanid": "11",
// //     "teid_user": "22",
// //     "aid": "13",
// //     "activityname": "diet",
// //     "uformid": "0",
// //     "uformname": "",
// //     "estart": "2021-04-14 21:30:00",
// //     "eend": "2021-04-14 21:35:00",
// //     "html": null,
// //     "otherinfo": {
// //       "NeedPhoto": "1",
// //       "NeedAudio": 0,
// //       "NeedVideo": 0,
// //       "NeedFile": 0
// //     },
// //     "remindin": "0",
// //     "remindin_type": "0",
// //     "ack": null,
// //     "alarm": "0",
// //     "uformdata": null,
// //     "ts": "2021-04-14 09:03:15",
// //     "deleted": "0",
// //     "hashtml": 0,
// //     "hascustform": 1,
// //     "hasform": 1,
// //     "saytext": "Eat Bed Time , 30 Mins Before Meal at 09:30 PM"
// //   },
// //   {
// //     "eid": "1329",
// //     "providerid": "1",
// //     "uid": "29",
// //     "title": " Glucose Postprandial BloodSugar , 120 Mins After Meal",
// //     "description": "Glucose Postprandial",
// //     "tplanid": "10",
// //     "teid_user": "6",
// //     "aid": "2",
// //     "activityname": "vitals",
// //     "uformid": "5",
// //     "uformname": "bloodsugar",
// //     "estart": "2021-04-14 22:00:00",
// //     "eend": "2021-04-14 22:05:00",
// //     "html": null,
// //     "otherinfo": {
// //       "NeedPhoto": 0,
// //       "NeedAudio": 0,
// //       "NeedVideo": 0,
// //       "NeedFile": 0
// //     },
// //     "remindin": "0",
// //     "remindin_type": "0",
// //     "ack": null,
// //     "alarm": "0",
// //     "uformdata": null,
// //     "ts": "2021-04-14 09:03:15",
// //     "deleted": "0",
// //     "hashtml": 0,
// //     "hascustform": 0,
// //     "hasform": 1,
// //     "saytext":
// //         "Check Vital Glucose Postprandial BloodSugar , 120 Mins After Meal at 10:00 PM"
// //   },
// //   {
// //     "eid": "1413",
// //     "providerid": "1",
// //     "uid": "29",
// //     "title": " Glucose Bedtime , 120 Mins After Meal",
// //     "description": "Glucose Bedtime",
// //     "tplanid": "10",
// //     "teid_user": "9",
// //     "aid": "2",
// //     "activityname": "vitals",
// //     "uformid": "0",
// //     "uformname": "",
// //     "estart": "2021-04-14 22:00:00",
// //     "eend": "2021-04-14 22:05:00",
// //     "html": null,
// //     "otherinfo": {
// //       "NeedPhoto": 0,
// //       "NeedAudio": 0,
// //       "NeedVideo": 0,
// //       "NeedFile": 0
// //     },
// //     "remindin": "0",
// //     "remindin_type": "0",
// //     "ack": null,
// //     "alarm": "0",
// //     "uformdata": null,
// //     "ts": "2021-04-14 09:03:15",
// //     "deleted": "0",
// //     "hashtml": 0,
// //     "hascustform": 0,
// //     "hasform": 0,
// //     "saytext":
// //         "Check Vital Glucose Bedtime , 120 Mins After Meal at 10:00 PM"
// //   }
// // ]);
// return RegimentResponseModel.fromJson([
// {
// "eid": "943",
// "providerid": "1",
// "uid": "29",
// "title": "  BloodPressure , 20 Mins Before and After Meal",
// "description": "",
// "tplanid": "10",
// "teid_user": "2",
// "aid": "2",
// "activityname": "vitals",
// "uformid": "1",
// "uformname": "bloodpressure",
// "estart": "2021-04-14 08:40:00",
// "eend": "2021-04-14 08:45:00",
// "html": null,
// "otherinfo":
// "{\"NeedPhoto\":0,\"NeedAudio\":0,\"NeedVideo\":0,\"NeedFile\":0}",
// "remindin": "0",
// "remindin_type": "0",
// "ack": "2021-04-14 09:03:26",
// "alarm": "1",
// "uformdata":
// "{\"Systolic\":{\"value\":\"111\",\"type\":\"number\",\"display\":\"111\",\"alarm\":0,\"amin\":\"40\",\"amax\":\"140\"},\"Diastolic\":{\"value\":\"222\",\"type\":\"number\",\"display\":\"222\",\"alarm\":1,\"amin\":\"35\",\"amax\":\"90\"},\"Pulse\":{\"value\":\"333\",\"type\":\"number\",\"display\":\"333\",\"alarm\":1,\"amin\":\"30\",\"amax\":\"130\"}}",
// "ts": "2021-04-14 09:03:26",
// "deleted": "0"
// },
// {
// "eid": "1203",
// "providerid": "1",
// "uid": "29",
// "title": " Glucose Fasting BloodSugar , 10 Mins Before Meal",
// "description": "Glucose Fasting",
// "tplanid": "10",
// "teid_user": "4",
// "aid": "2",
// "activityname": "vitals",
// "uformid": "5",
// "uformname": "bloodsugar",
// "estart": "2021-04-14 08:50:00",
// "eend": "2021-04-14 08:55:00",
// "html": null,
// "otherinfo":
// "{\"NeedPhoto\":0,\"NeedAudio\":0,\"NeedVideo\":0,\"NeedFile\":0}",
// "remindin": "0",
// "remindin_type": "0",
// "ack": "2021-04-14 09:03:30",
// "alarm": "0",
// "uformdata":
// "{\"BloodSugar\":{\"value\":\"123\",\"type\":\"number\",\"display\":\"123\",\"alarm\":0,\"amin\":\"\",\"amax\":\"\"}}",
// "ts": "2021-04-14 09:03:30",
// "deleted": "0"
// },
// {
// "eid": "944",
// "providerid": "1",
// "uid": "29",
// "title": "  BloodPressure , 20 Mins Before and After Meal",
// "description": "",
// "tplanid": "10",
// "teid_user": "2",
// "aid": "2",
// "activityname": "vitals",
// "uformid": "1",
// "uformname": "bloodpressure",
// "estart": "2021-04-14 09:20:00",
// "eend": "2021-04-14 09:25:00",
// "html": null,
// "otherinfo":
// "{\"NeedPhoto\":0,\"NeedAudio\":0,\"NeedVideo\":0,\"NeedFile\":0}",
// "remindin": "0",
// "remindin_type": "0",
// "ack": "2021-04-14 09:03:38",
// "alarm": "1",
// "uformdata":
// "{\"Systolic\":{\"value\":\"333\",\"type\":\"number\",\"display\":\"333\",\"alarm\":1,\"amin\":\"40\",\"amax\":\"140\"},\"Diastolic\":{\"value\":\"222\",\"type\":\"number\",\"display\":\"222\",\"alarm\":1,\"amin\":\"35\",\"amax\":\"90\"},\"Pulse\":{\"value\":\"111\",\"type\":\"number\",\"display\":\"111\",\"alarm\":0,\"amin\":\"30\",\"amax\":\"130\"}}",
// "ts": "2021-04-14 09:03:38",
// "deleted": "0"
// },
// {
// "eid": "5101",
// "providerid": "1",
// "uid": "29",
// "title": " Pre Breakfast , 10 Mins After Wakeup",
// "description": "Pre Breakfast",
// "tplanid": "11",
// "teid_user": "60",
// "aid": "13",
// "activityname": "diet",
// "uformid": "0",
// "uformname": "",
// "estart": "2021-04-15 06:10:00",
// "eend": "2021-04-15 06:15:00",
// "html": null,
// "otherinfo":
// "{\"NeedPhoto\":0,\"NeedAudio\":0,\"NeedVideo\":0,\"NeedFile\":0}",
// "remindin": "0",
// "remindin_type": "0",
// "ack": "2021-04-15 18:10:16",
// "alarm": "0",
// "uformdata":
// "{\"PreBKFST\":{\"value\":\"0||2|\",\"type\":\"checkbox\",\"display\":\"Aamla water + 2 Almonds,Tulasi water + 2 Almonds\",\"alarm\":0,\"amin\":\"\",\"amax\":\"\"},\"Notes\":{\"value\":\"\",\"type\":\"text\",\"display\":\"\",\"alarm\":0,\"amin\":\"\",\"amax\":\"\"},\"#otherdata\":{\"PHOTO\":{\"name\":\"\",\"url\":\"\"},\"AUDIO\":{\"name\":\"\",\"url\":\"\"},\"FILE\":{\"name\":\"\",\"url\":\"\"},\"VIDEO\":{\"name\":\"\",\"url\":\"\"}}}",
// "ts": "2021-04-15 18:10:16",
// "deleted": "0"
// },
// {
// "eid": "4561",
// "providerid": "1",
// "uid": "29",
// "title": "  BloodPressure , 20 Mins Before and After Meal",
// "description": "",
// "tplanid": "10",
// "teid_user": "46",
// "aid": "2",
// "activityname": "vitals",
// "uformid": "1",
// "uformname": "bloodpressure",
// "estart": "2021-04-15 08:40:00",
// "eend": "2021-04-15 08:45:00",
// "html": null,
// "otherinfo":
// "{\"NeedPhoto\":0,\"NeedAudio\":0,\"NeedVideo\":0,\"NeedFile\":0}",
// "remindin": "0",
// "remindin_type": "0",
// "ack": "2021-04-15 11:55:45",
// "alarm": "1",
// "uformdata":
// "{\"Systolic\":{\"value\":\"120\",\"type\":\"number\",\"display\":\"120\",\"alarm\":0,\"amin\":\"40\",\"amax\":\"140\"},\"Diastolic\":{\"value\":\"12\",\"type\":\"number\",\"display\":\"12\",\"alarm\":1,\"amin\":\"35\",\"amax\":\"90\"},\"Pulse\":{\"value\":\"60\",\"type\":\"number\",\"display\":\"60\",\"alarm\":0,\"amin\":\"30\",\"amax\":\"130\"},\"Test\":{\"value\":\"0\",\"type\":\"lookup\",\"display\":\"0\",\"alarm\":0,\"amin\":\"\",\"amax\":\"\"},\"check\":{\"value\":\"\",\"type\":\"check\",\"display\":\"\",\"alarm\":0,\"amin\":\"\",\"amax\":\"\"},\"Radio\":{\"value\":\"\",\"type\":\"radio\",\"display\":\"\",\"alarm\":0,\"amin\":\"\",\"amax\":\"\"}}",
// "ts": "2021-04-15 11:55:45",
// "deleted": "0"
// }
// ]);
