class mockDoctorsData {
  var doctorList = {
    'status': 'success',
    'data': [
      {
        'userid': '137',
        'username': 'Doctor0',
        'fullname': 'Dr.Amit Joshi',
        'age': '56',
        'history': '0',
        'profileimage': 'Doctor0.jpg',
        'address': 'Texas, USA',
        "countryCode": '23554',
        'phoneNumber': '+1 54876215',
        'status': '1',
        'conditions':
            'He has been working as Orothologist for more than 10 years',
        'isBookMarked': true,
        'isAvailable':'available',
        'consultation_fee':'350',
        'specialist':'Orthopedic And Sports Surgeon',
        'city':'Chennai'
      },
      {
        'userid': '138',
        'username': 'Doctor1',
        'fullname': 'Dr.Khurana',
        'age': '45',
        'history': '0',
        'profileimage': 'Doctor1.jpg',
        'address': 'Bangalore, Karnataka',
        "countryCode": '532464',
        'phoneNumber': '9564562365',
        'status': '0',
        'conditions': 'General Physician',
        'isBookMarked': true,
         'isAvailable':'available',
        'consultation_fee':'150',
        'specialist':'Fertility specialist',
        'city':'Banglore'
      },
      {
        'userid': '139',
        'username': 'Doctor2',
        'fullname': 'Dr.Sumathy',
        'age': '40',
        'history': '0',
        'profileimage': 'Doctor2.jpg',
        'address': 'Trichy, Tamilnadu',
        "countryCode": '620001',
        'phoneNumber': '8556665545',
        'status': '1',
        'conditions': 'She is working as an Anesthesiologists for 3 years',
        'isBookMarked': true,
         'isAvailable':'busy',
        'consultation_fee':'250',
        'specialist':'General Physician',
        'city':'Delhi'
      },
      {
        'userid': '140',
        'username': 'Doctor3',
        'fullname': 'Dr.Chithra',
        'age': '45',
        'history': '0',
        'profileimage': 'Doctor3.jpg',
        'address': 'vijaywada, Andhara',
        "countryCode": '364555',
        'phoneNumber': '9564562365',
        'status': '0',
        'conditions': 'Cardiologists',
        'isBookMarked': true,
         'isAvailable':'available',
        'consultation_fee':'350',
        'specialist':'Pediatrician',
        'city':'Banglore'
      },
      {
        'userid': '140',
        'username': 'Doctor3',
        'fullname': 'Dr.Chitu',
        'age': '45',
        'history': '0',
        'profileimage': 'Doctor3.jpg',
        'address': 'vijaywada, Andhara',
        "countryCode": '364555',
        'phoneNumber': '9564562365',
        'status': '1',
        'conditions': 'Cardiologists',
        'isBookMarked': false,
         'isAvailable':'available',
        'consultation_fee':'350',
        'specialist':'Dermotologist',
        'city':'Chennai'
      },
      {
        'userid': '140',
        'username': 'Doctor3',
        'fullname': 'Dr.Chithra Krishnan',
        'age': '45',
        'history': '0',
        'profileimage': 'Doctor3.jpg',
        'address': 'vijaywada, Andhara',
        "countryCode": '364555',
        'phoneNumber': '9564562365',
        'status': '1',
        'conditions': 'Cardiologists',
        'isBookMarked': false,
         'isAvailable':'busy',
        'consultation_fee':'550',
        'specialist':'Gynocologist',
        'city':'Chennai'
      },
      {
        'userid': '140',
        'username': 'Doctor3',
        'fullname': 'Dr.Charu',
        'age': '45',
        'history': '0',
        'profileimage': 'Doctor3.jpg',
        'address': 'vijaywada, Andhara',
        "countryCode": '364555',
        'phoneNumber': '9564562365',
        'status': '0',
        'conditions': 'Cardiologists',
        'isBookMarked': false,
         'isAvailable':'available',
        'consultation_fee':'550',
        'specialist':'Eye specialist',
        'city':'Chennai'
      },
    ]
  };
}
